/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Message = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Comment = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addEssaysComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addHomeComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addPoemsComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addStoriesComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getContactMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getEssaysComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getHomeComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getPoemsComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  'getStoriesComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Message = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Comment = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addEssaysComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addHomeComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addPoemsComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addStoriesComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getContactMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getEssaysComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getHomeComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getPoemsComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
    'getStoriesComments' : IDL.Func([], [IDL.Vec(Comment)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };