/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
}
export interface LiteraryContent {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'author' : Principal,
  'timestamp' : bigint,
}
export interface Message {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[string, string, string], undefined>,
  'addContactMessage' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDraft' : ActorMethod<[string, string], string>,
  'deleteContent' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[string], Array<Comment>>,
  'getContactMessages' : ActorMethod<[], Array<Message>>,
  'getContentById' : ActorMethod<[string], [] | [LiteraryContent]>,
  'getDailyVisits' : ActorMethod<[bigint], bigint>,
  'getDrafts' : ActorMethod<[], Array<LiteraryContent>>,
  'getPublishedContent' : ActorMethod<[], Array<LiteraryContent>>,
  'getTotalVisits' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishContent' : ActorMethod<[string], undefined>,
  'recordVisit' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'unpublishContent' : ActorMethod<[string], undefined>,
  'updateDraft' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];